# Generated by Django 3.2.1 on 2024-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0004_alter_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
