# Generated by Django 3.2.1 on 2024-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0005_alter_shipping_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='lattitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
